# Generated by Django 5.0.6 on 2024-06-04 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0002_alter_customuser_email_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
